Makefile CM revised

diff --git a/makefile.cm b/makefile.cm
--- a/makefile.cm
+++ b/makefile.cm
@@ -30,9 +30,13 @@ $(shell rm -f .show-update-msg)
 pref := SECONDO_CD
 net := $(SECONDO_SDK_ROOT)/$(pref)
 
-ifndef $(websrv)
+# local directory for tar archives
 websrv := $(PWD)/websrv
-endif
+
+define mkwebdir
+if [ ! -d $(websrv) ]; then mkdir -p $(websrv); fi
+endef
+
 
 # Rules for copying configuration scripts
 SCRIPT_DIR := ./CM-Scripts
@@ -96,26 +100,31 @@ show-separator:
 INSTALL_SCRIPTS := $(net)/scripts/winsetup.sh \
 		   $(net)/scripts/libutil.sh
 
-WIN_SRC := $(net)/secondo$(VERSION)-CP1252.zip
+WIN_SRC := $(net)/secondo-$(tag)-CP1252.zip
 
-LIN_SRC := $(net)/secondo$(VERSION)-LAT1.tar.gz
+LIN_SRC := $(net)/secondo-$(tag)-LAT1.tar.gz
 
-SRC_FILES := $(WIN_SRC) $(WIN_BIG) $(LIN_SRC) $(LIN_BIG) 
+SRC_FILES := $(WIN_SRC) $(LIN_SRC)
 
-INSTGUIDE_FILES := $(net)/Linux-Installation-Guide.pdf \
- 		   $(net)/Windows-Installation-Guide.pdf
  
 .PHONY: dist
-dist: tag-version  dist-scripts src-archives $(INSTGUIDE_FILES) linux-sdk win32-sdk
+dist: checkroot tag-version dist-scripts src-archives linux-sdk win32-sdk
+
+.PHONY: checkroot
+checkroot:
+ifndef SECONDO_SDK_ROOT
+	@echo -e "\nError: SECONDO_SDK_ROOT not defined!\n"; exit 1
+else
+	@if [ ! -e $(net) ]; then \
+	echo -e "\nDirectory net=\"$(net)\" does not exist!\n"; exit 2; fi
+endif
+
 
 
 .PHONY: dist-scripts
 dist-scripts: $(net)/installsdk $(INSTALL_SCRIPTS)
 
 
-define mkwebdir
-if [ ! -d $(websrv) ]; then mkdir -p $(websrv); fi
-endef
 
 .PHONY: linux-sdk
 linux-sdk: 
@@ -163,28 +172,18 @@ demo: $(BIN_FILES)
 
 .PHONY: tag-version
 tag-version:
-ifndef $(tag)
+ifndef tag
 	@echo -e "\n Error: Variable tag not set! \n"; exit 1
 else
-	cvs tag -F $(tag) 
+	cvs -Q tag -F $(tag) 
 endif
 
+fileList := .SRC_FILES
 .PHONY: src-archives
-src-archives: secondo/makefile
+src-archives: .srcfileList
 	$(mkwebdir)
-	rm -rf $(SRC_FILES) .SRC_FILES
-	find secondo ! -type d \
-                     ! -name "opt" \
-                     ! -name "geo" \
-                     ! -name ".sda" \
-                     ! -name ".sxd" \
-                     ! -name ".canvas" \
-                     ! -path "*/Data/*" \
-                     ! -path "*/Generators/TPC-H/*" \
-                     ! -path "*/Algebras/NauticalMap*" \
-                     ! -name "*.pdf" > .SRC_FILES
-	find secondo/Data ! -type d -size -10k >> .SRC_FILES
-	tar -czf $(LIN_SRC) -T .SRC_FILES
+	rm -rf $(SRC_FILES)
+	tar -czf $(LIN_SRC) -T $<
 	find secondo ! \( \
           -type d \
           -or -name "*.bmp" \
@@ -204,11 +203,24 @@ src-archives: secondo/makefile
           -or -path "*javazoom*" \
         \) \
         -exec recode lat1..cp1252 {} \;
-	cat SRC_FILES | zip -9 -r $(WIN_SRC) -@ > /dev/null
-#	rm -r secondo
+	cat $< | zip -9 -r $(WIN_SRC) -@ > /dev/null
+	rm -rf secondo
+
+.srcfileList: secondo/makefile
+	find secondo ! -type d \
+                     ! -name "opt" \
+                     ! -name "geo" \
+                     ! -name ".sda" \
+                     ! -name ".sxd" \
+                     ! -name ".canvas" \
+                     ! -path "*/Data/*" \
+                     ! -path "*/Generators/TPC-H/*" \
+                     ! -path "*/Algebras/NauticalMap*" \
+                     ! -name "*.pdf" > $@ 
+	find secondo/Data ! -type d -size -10k >> $@
 
 secondo/makefile:
-	cvs -Q export -rHEAD secondo 
+	cvs -Q export -r$(tag) secondo 
 
 
 $(net)/installsdk: $(SCRIPT_DIR)/install.bash
@@ -219,8 +231,6 @@ $(net)/scripts/%.sh: $(SCRIPT_DIR)/%.sh
 	cp $< $@
 	chmod ugo+x $@
 
-$(net)/%.pdf: Documents/Installation/%.ps
-	ps2pdf $< $@
 
 # store modified files in a tar archive
 .PHONY: backup 
