Installation and environment setup scripts reorganized

diff --git a/CM-Scripts/secondorc b/CM-Scripts/secondorc
--- a/CM-Scripts/secondorc
+++ b/CM-Scripts/secondorc
@@ -18,6 +18,8 @@
 #
 # DO NOT CHANGE THIS FILE!
 
+declare -i ERR=0
+
 # Some function definitions
 
 # $1: file
@@ -40,58 +42,61 @@ fi
 # $2: directory
 function checkDir {
 
-if ! [ -d $buildDir ]; then
-  printf "%s"   "Error: $1. Directory \"${2}\" is "
+if ! [ -d $2 ]; then
+  printf "%s"   "Error: $1 Directory \"${2}\" is "
   printf "%s\n\n" "not present!"
-  ok="false" 
   let ERR++
   return 1
 fi
 return 0
 }
 
-# include alias definitions and default values
-#alias secinit > /dev/null 2>&1
-#if [ $? -ne 0 ]; then
-  includeDefs ~/.secondo.aliases
-#fi
-shopt -s expand_aliases
+
+# $1: variable name 
+# $2: variable value 
+function checkVar {
+
+if [ "$2" == "" ]; then
+  printf "%s\n\n"   "Error: Variable $1 is not set!"
+  let ERR++
+  return 1
+fi
+return 0
+}
 
 # define short variables for important base directories
 buildDir=$SECONDO_BUILD_DIR
 sdkDir=$SECONDO_SDK
 platform=$SECONDO_PLATFORM
 
-ok="true"
-declare -i ERR=0
+# include alias definitions and default values
+checkDir "Testing if variable SECONDO_SDK points to an existing directory." $sdkDir
+
+checkDir "Testing if variable SECONDO_BUILD_DIR points to an existing directory." $buildDir
+
+# test if $buildDir seems to be a SECONDO source tree 
+checkDir "SECONDO_BUILD_DIR seems not to point to a secondo source tree" ${buildDir}/Algebras/Standard-C++
+
 if [ "$platform" != "linux" ]; then
   if [ "$platform" != "mac_osx" ]; then
     if [ "$platform" != "win32" ]; then
       printf "%s\n" "Error: SECONDO_PLATFORM must be set to linux, mac_osx or win32!"
-      ok="false" 
+      let ERR++
     fi
   fi
 fi 
 
-checkDir "Testing if variable SECONDO_BUILD_DIR points to an existing directory " $buildDir
-checkDir "Testing if variable SECONDO_SDK points to an existing directory " $sdkDir
+echo "ERR="$ERR
+if [ $ERR -eq 0 ]; then
 
-# test if $buildDir seems to be a SECONDO source tree 
-checkDir "$buildDir seems not to point to a secondo source tree" ${buildDir}/Algebras/Standard-C++
-
-if [ $? -ne 0 ]; then
-  printf "%s\n" "Setting \$SECONDO_BUILD_DIR=\$HOME/secondo."
-  buildDir=${HOME}/secondo
-fi
-
+includeDefs $SECONDO_SDK/secondo.aliases
+shopt -s expand_aliases
 
 # include platform specific definitions
-includeDefs ${sdkDir}/secondo.config
-
-if [ "$ok" == "true" ]; then
+includeDefs ${sdkDir}/secondo.config.$platform
 
 # set common variables
-includeDefs ${sdkDir}/bin/setvar.bash ${buildDir}
+includeDefs ${sdkDir}/secondo.setroot ${buildDir}
 
 # Berkeley-DB Library
 #
@@ -110,18 +115,19 @@ fi
 export BERKELEY_DB_LIB
 
 # Check if important directories are present
-checkDir "Testing J2SDKROOT " $J2SDKROOT
+checkDir "Testing J2SDK_ROOT " $J2SDK_ROOT
 checkDir "Testing PL_LIB_DIR " $PL_LIB_DIR
 
 if [ $ERR -ne 0 ]; then
   printf "%s"   "Please check your installation and consult the configuration files"
 fi
 
-# end of "$ok"="true"
+secenv
+
+# end of $ERR == 0 
 fi
 
-catvar 
+ 
 printf "\n%s\n"  "In case of trouble consult the environment setup files:"
-printf "%s\n"    "  ${sdkDir}/secondo.config"
-printf "%s\n"    "  ${sdkDir}/secondorc"
+printf "%s\n"    "  ${sdkDir}/secondo.config.*"
 printf "%s\n\n"  "  ${sdkDir}/secondo.setroot"
