The Traces2SecDB script can now extract different informations

diff --git a/Tools/Converter/NMEA2Secondo/Traces2SecDB b/Tools/Converter/NMEA2Secondo/Traces2SecDB
--- a/Tools/Converter/NMEA2Secondo/Traces2SecDB
+++ b/Tools/Converter/NMEA2Secondo/Traces2SecDB
@@ -4,27 +4,88 @@
 #
 
 #set defaults
-Converter=NMEA2Secondo
-Type=mpoint
-Name=trip
+TRACE=false
+HEIGHT=false
+SPEED=false
 
-if [ "$1" = "-height" ]; then
-   Converter=NMEA2MReal
-   Type=mreal
-   Name=height 
-   shift
-else
-   if [ "$1" = "-speed" ]; then
-      Converter=NMEA_SpeedExtractor
-      Type=mreal
-      Name=speed
-      shift
-   fi
+function showUsage() {
+  echo "usage: Traces2SecDB [options] <relation name> <file_1> ... <file_n>" >&2
+  echo "allowed options: " >&2
+  echo " -trace: extracts the trip as a moving point" >&2
+  echo " -height: extracts the height as a moving real" >&2
+  echo " -speed: extracts the speed as a moving real" >&2
+  echo " -all: the same as -trace -height -speed" >&2
+  echo " -help: this help message" >&2
+  echo " Note: if no option is given, the tript is extracted from the nmea files" >&2
+  exit 1
+}
+
+function extractOption() {
+   options="$1"
+   pos=0
+   length=${#options}
+   while [ "$pos" -lt  "$length" ]; do
+      arg=${options:pos:1}
+      case $arg in 
+        h)
+           HEIGHT=true
+           ;;
+        t)
+           TRACE=true
+           ;;
+        s)
+           SPEED=true
+           ;;
+        *) 
+           echo "unknown argument : -$options" >&2
+           showUsage
+           ;;
+       esac
+      (( pos += 1 )) 
+   done 
+}
+
+# parse arguments without getopts 
+OPTION=$1
+OptId=${OPTION:0:1}
+while [ "$OptId" = "-" ]; do
+  case $OPTION in
+   -height) 
+             HEIGHT=true
+             ;;
+   -trace)
+             TRACE=true
+             ;;
+   -speed)
+             SPEED=true
+             ;;
+   -all)     
+             HEIGHT=true
+             SPEED=true
+             TRACE=true
+             ;;
+    -help)   
+             showUsage
+             ;;
+    *)       
+             extractOption ${OPTION:1} 
+             ;;
+  esac
+  shift
+  OPTION=$1
+  OptId=${OPTION:0:1}
+done
+
+
+if [  "$TRACE" = "false"  -a  "$SPEED" = "false" -a "$HEIGHT" = "false" ]; then
+# if no arguments are given, we switch to trace extraction
+   TRACE=true
 fi
 
-if [ -z "$*" ]; then
-   echo "usage: Traces2SecDB [-hight | -speed ] <name of the relation> trace_1...trace_n"
-   exit -1
+
+if [ -z $1 ]; then
+  echo "missing name of relation " >&2
+  showUsage
 fi
 
 NAME=$1
@@ -35,7 +96,19 @@ ARGUMENTS=" file local 0.0 -value";
 
 # print header
 
-echo '( OBJECT '$NAME ' () (rel (tuple( (name string) ('$Name' '$Type')))) '
+echo '( OBJECT '$NAME ' () (rel (tuple(' 
+echo "       (name string) "
+if [ "$TRACE" = "true" ]; then
+    echo "       (trip mpoint) "
+fi
+if [ "$SPEED" = "true" ]; then
+    echo "       (speed mreal) "
+fi
+if [ "$HEIGHT" = "true" ]; then
+    echo "       (height mreal) "
+fi
+echo " )))"
+# open value list
 echo '  ('
 
 for f in $* 
@@ -49,8 +122,26 @@ do
   else
      name=$f
   fi
-  echo -ne "\""$name"\" " 
-  java -classpath $CLASSPATH $Converter $f $ARGUMENTS
+  echo -ne "\""$name"\" "
+  if [ "$TRACE" = "true" ]; then 
+      java -classpath $CLASSPATH NMEA2Secondo $f $ARGUMENTS
+  fi
+  if [ $? -ne "0" ]; then
+    echo "problem in calling java program" >&2
+    exit -1
+  fi
+
+  if [ "$SPEED" = "true" ]; then 
+      java -classpath $CLASSPATH NMEA_SpeedExtractor $f $ARGUMENTS
+  fi
+  if [ $? -ne "0" ]; then
+    echo "problem in calling java program" >&2
+    exit -1
+  fi
+
+  if [ "$HEIGHT" = "true" ]; then 
+      java -classpath $CLASSPATH NMEA2MReal $f $ARGUMENTS
+  fi
   if [ $? -ne "0" ]; then
     echo "problem in calling java program" >&2
     exit -1
